name: "🚀 Deploy to WP Engine"

on:
    workflow_call:
        inputs:
            staging_environment_name:
                description: The name of the staging environment in WP Engine.
                required: true
                type: string
            production_environment_name:
                description: The name of the production environment in WP Engine.
                required: true
                type: string
            node_version:
                description: The required version of node passed from the caller workflow.
                required: true
                type: string
            src_path:
                description: Optional path to specify a directory within the repo to deploy from. Ex. "wp-content/themes/soar/". Defaults to root of repo filesystem as source.
                required: false
                default: .
                type: string
            remote_path:
                description: Optional path to specify a directory destination to deploy to. Ex. "wp-content/themes/soar/". Defaults to WordPress root directory on WP Engine.
                required: false
                default: .
                type: string
            rsync_flags:
                description: Optional rsync flags such as '--delete' or '--exclude-from'. '-a' preserves symbolic links, timestamps, user permissions and ownership. '-z' is for compression. '-v' is for verbose output. '-r' is for recursive directory scanning. Defaults to '-azvr --inplace --delete --exclude-from=exclude.txt'.
                required: false
                default: -azvr --inplace --delete --exclude-from=exclude.txt
                type: string
            
defaults:
    run:
        shell: pwsh

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
          - name: "🚚 Get Latest Code"
            uses: actions/checkout@v3
          - name: ⚙️ Use Node.js ${{ inputs.node_version }}
            uses: actions/setup-node@v2
            with:
                node-version: ${{ inputs.node_version }}
          - name: "🛠️ Build"
            run: |
                npm ci
                npm run build
          - name: "🥷 Conditional WPEngine environment"
            if: github.event_name != 'workflow_dispatch'
            uses: haya14busa/action-cond@v1.0.0
            id: environment
            with:
                cond: ${{ github.ref_name == 'production' }}
                if_true: ${{ inputs.production_environment_name }}
                if_false: ${{ inputs.staging_environment_name }}
          - name: Deploy to WP Engine - ${{ steps.environment.outputs.value || inputs.staging_environment_name }}
            uses: wpengine/github-action-wpe-site-deploy@v3
            with:
                WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
                WPE_ENV: ${{ steps.environment.outputs.value || inputs.staging_environment_name }}
                SRC_PATH: ${{ inputs.src_path }}
                REMOTE_PATH: ${{ inputs.remote_path }}
                FLAGS: ${{ inputs.rsync_flags }}
                CACHE_CLEAR: TRUE